# Estatística para Machine Learning

## 4. Medidas de posição e dispersão

### Base de dados

In [25]:
import numpy as np
import statistics
from scipy import stats
import math

In [26]:
dados = np.array([150, 151, 152, 152, 153, 154, 155, 155, 155, 155, 156, 156, 156,
                  157, 158, 158, 160, 160, 160, 160, 160, 161, 161, 161, 161, 162,
                  163, 163, 164, 164, 164, 165, 166, 167, 168, 168, 169, 170, 172,
                  173])

### Média aritmética simples

In [4]:
dados.sum() / len(dados)

160.375

In [5]:
dados.mean()

160.375

In [6]:
statistics.mean(dados)

160

### Moda

In [7]:
statistics.mode(dados)

160

In [8]:
stats.mode(dados)

ModeResult(mode=array([160]), count=array([5]))

### Mediana

In [9]:
dados_impar = [150, 151, 152, 152, 153, 154, 155, 155, 155]

#### Cálculo manual (ímpar)

In [10]:
posicao = len(dados_impar) / 2 
posicao

4.5

In [11]:
posicao = math.ceil(posicao)
posicao

5

In [12]:
dados_impar[posicao - 1]

153

#### Cálculo manual (par)

In [13]:
posicao = len(dados) // 2
posicao

20

In [14]:
dados[posicao - 1], dados[posicao]

(160, 160)

In [15]:
mediana = (dados[posicao - 1] + dados[posicao]) / 2
mediana

160.0

#### Bibliotecas

In [16]:
np.median(dados_impar)

153.0

In [17]:
np.median(dados)

160.0

In [18]:
statistics.median(dados_impar)

153

In [19]:
statistics.median(dados)

160.0

### Média aritmética ponderada

In [20]:
notas = np.array([9, 8, 7, 3])
pesos = np.array([1, 2, 3, 4])

In [21]:
(9 * 1 + 8 * 2 + 7 * 3 + 3 * 4) / (1 + 2 + 3 + 4)

5.8

In [22]:
media_ponderada = (notas * pesos).sum() / pesos.sum()
media_ponderada

5.8

In [23]:
np.average(notas, weights=pesos)

5.8

### Média aritmética, moda e mediana com distribuição de frequência (dados agrupados)

In [1]:
dados = {'inferior': [150, 154, 158, 162, 166, 170],
         'superior': [154, 158, 162, 166, 170, 174],
         'fi': [5, 9, 11, 7, 5, 3]}

In [2]:
import pandas as pd
dataset = pd.DataFrame(dados)
dataset

inferior  superior  fi
0       150       154   5
1       154       158   9
2       158       162  11
3       162       166   7
4       166       170   5
5       170       174   3

In [3]:
dataset['xi'] = (dataset['superior'] + dataset['inferior']) / 2
dataset

inferior  superior  fi     xi
0       150       154   5  152.0
1       154       158   9  156.0
2       158       162  11  160.0
3       162       166   7  164.0
4       166       170   5  168.0
5       170       174   3  172.0

In [4]:
dataset['fi.xi'] = dataset['fi'] * dataset['xi']
dataset

inferior  superior  fi     xi   fi.xi
0       150       154   5  152.0   760.0
1       154       158   9  156.0  1404.0
2       158       162  11  160.0  1760.0
3       162       166   7  164.0  1148.0
4       166       170   5  168.0   840.0
5       170       174   3  172.0   516.0

In [5]:
dataset['Fi'] = 0
dataset

inferior  superior  fi     xi   fi.xi  Fi
0       150       154   5  152.0   760.0   0
1       154       158   9  156.0  1404.0   0
2       158       162  11  160.0  1760.0   0
3       162       166   7  164.0  1148.0   0
4       166       170   5  168.0   840.0   0
5       170       174   3  172.0   516.0   0

In [6]:
frequencia_acumulada = []
somatorio = 0
for linha in dataset.iterrows():
  #print(linha[1])
  #print(linha[1][2])
  somatorio += linha[1][2]
  frequencia_acumulada.append(somatorio)

In [7]:
frequencia_acumulada

[5.0, 14.0, 25.0, 32.0, 37.0, 40.0]

In [8]:
dataset['Fi'] = frequencia_acumulada
dataset

inferior  superior  fi     xi   fi.xi    Fi
0       150       154   5  152.0   760.0   5.0
1       154       158   9  156.0  1404.0  14.0
2       158       162  11  160.0  1760.0  25.0
3       162       166   7  164.0  1148.0  32.0
4       166       170   5  168.0   840.0  37.0
5       170       174   3  172.0   516.0  40.0

#### Média

In [9]:
dataset['fi'].sum(), dataset['fi.xi'].sum()

(40, 6428.0)

In [10]:
dataset['fi.xi'].sum() / dataset['fi'].sum()

160.7

#### Moda

In [12]:
dataset['fi'].max()

11

In [13]:
dataset[dataset['fi'] == dataset['fi'].max()]

inferior  superior  fi     xi   fi.xi    Fi
2       158       162  11  160.0  1760.0  25.0

In [14]:
dataset[dataset['fi'] == dataset['fi'].max()]['xi'].values[0]

160.0

#### Mediana

In [15]:
dataset

inferior  superior  fi     xi   fi.xi    Fi
0       150       154   5  152.0   760.0   5.0
1       154       158   9  156.0  1404.0  14.0
2       158       162  11  160.0  1760.0  25.0
3       162       166   7  164.0  1148.0  32.0
4       166       170   5  168.0   840.0  37.0
5       170       174   3  172.0   516.0  40.0

In [16]:
fi_2 = dataset['fi'].sum() / 2
fi_2

20.0

In [17]:
limite_inferior, frequencia_classe, id_frequencia_anterior = 0, 0, 0
for linha in dataset.iterrows():
  #print(linha)
  limite_inferior = linha[1][0]
  frequencia_classe = linha[1][2]
  id_frequencia_anterior = linha[0]
  if linha[1][5] >= fi_2:
    id_frequencia_anterior -= 1
    break

In [18]:
limite_inferior, frequencia_classe, id_frequencia_anterior

(158.0, 11.0, 1)

In [19]:
Fi_anterior = dataset.iloc[[id_frequencia_anterior]]['Fi'].values[0]
Fi_anterior

14.0

In [20]:
mediana = limite_inferior + ((fi_2 - Fi_anterior) * 4) / frequencia_classe
mediana

160.1818181818182

#### Função completa

In [21]:
def get_estatisticas(dataframe):
  media = dataset['fi.xi'].sum() / dataset['fi'].sum()
  moda = dataset[dataset['fi'] == dataset['fi'].max()]['xi'].values[0]

  fi_2 = dataset['fi'].sum() / 2
  limite_inferior, frequencia_classe, id_frequencia_anterior = 0, 0, 0
  for i, linha in enumerate(dataset.iterrows()):
    limite_inferior = linha[1][0]
    frequencia_classe = linha[1][2]
    id_frequencia_anterior = linha[0]
    if linha[1][5] >= fi_2:
      id_frequencia_anterior -= 1
      break
  Fi_anterior = dataset.iloc[[id_frequencia_anterior]]['Fi'].values[0]
  mediana = limite_inferior + ((fi_2 - Fi_anterior) * 4) / frequencia_classe

In [22]:
get_estatisticas(dataset)

### Média geométrica, harmônica e quadrática

#### Média geométrica

In [23]:
from scipy.stats.mstats import gmean

In [27]:
gmean(dados)

160.26958390038902

#### Média harmônica

In [28]:
from scipy.stats.mstats import hmean

In [29]:
hmean(dados)

160.16471947994674

#### Média quadrática

In [30]:
def quadratic_mean(dados):
  return math.sqrt(sum(n * n for n in dados) / len(dados))

In [31]:
quadratic_mean(dados)

160.48091786876097

### Quartis

In [32]:
dados_impar = [150, 151, 152, 152, 153, 154, 155, 155, 155]

#### Cálculo manual

In [33]:
np.median(dados_impar)

153.0

In [34]:
posicao_mediana = math.floor(len(dados_impar) / 2)
posicao_mediana

4

In [35]:
esquerda = dados_impar[0:posicao_mediana]
esquerda

[150, 151, 152, 152]

In [36]:
np.median(esquerda)

151.5

In [37]:
direita = dados_impar[posicao_mediana + 1:]
direita

[154, 155, 155, 155]

In [38]:
np.median(direita)

155.0

#### Bibliotecas

#### Numpy

In [39]:
np.quantile(dados_impar, 0.5)

153.0

In [40]:
np.quantile(dados_impar, 0.75)

155.0

In [41]:
np.quantile(dados_impar, 0.25)

152.0

In [42]:
esquerda2 = dados_impar[0:posicao_mediana + 1]
esquerda2

[150, 151, 152, 152, 153]

In [43]:
np.median(esquerda2)

152.0

In [44]:
np.quantile(dados, 0.25), np.quantile(dados, 0.50), np.quantile(dados, 0.75)

(155.75, 160.0, 164.0)

#### Scipy

In [45]:
stats.scoreatpercentile(dados, 25), stats.scoreatpercentile(dados, 50), stats.scoreatpercentile(dados, 75)

(155.75, 160.0, 164.0)

#### Pandas

In [46]:
import pandas as pd
dataset = pd.DataFrame(dados)
dataset.head()

0
0  150
1  151
2  152
3  152
4  153

In [47]:
dataset.quantile([0.25, 0.5, 0.75])

0
0.25  155.75
0.50  160.00
0.75  164.00

In [48]:
dataset.describe()

0
count   40.000000
mean   160.375000
std      5.903877
min    150.000000
25%    155.750000
50%    160.000000
75%    164.000000
max    173.000000

### Quartis com distribuição de frequência

In [49]:
dataset

0
0   150
1   151
2   152
3   152
4   153
5   154
6   155
7   155
8   155
9   155
10  156
11  156
12  156
13  157
14  158
15  158
16  160
17  160
18  160
19  160
20  160
21  161
22  161
23  161
24  161
25  162
26  163
27  163
28  164
29  164
30  164
31  165
32  166
33  167
34  168
35  168
36  169
37  170
38  172
39  173

In [50]:
def get_quartil(dataframe, q1 = True):
  if q1 == True:
    fi_4 = dataset['fi'].sum() / 4
  else:
    fi_4 = (3 * dataset['fi'].sum()) / 4
  
  limite_inferior, frequencia_classe, id_frequencia_anterior = 0, 0, 0
  for linha in dataset.iterrows():
    limite_inferior = linha[1][0]
    frequencia_classe = linha[1][2]
    id_frequencia_anterior = linha[0]
    if linha[1][5] >= fi_4:
      id_frequencia_anterior -= 1
      break
  Fi_anterior = dataset.iloc[[id_frequencia_anterior]]['Fi'].values[0]
  q = limite_inferior + ((fi_4 - Fi_anterior) * 4) / frequencia_classe

  return q

In [51]:
get_quartil(dados), get_quartil(dados, q1 = False)

KeyError: 'fi'

#### Percentis

In [52]:
np.median(dados)

160.0

In [53]:
np.quantile(dados, 0.5)

160.0

In [54]:
np.percentile(dados, 50)

160.0

In [55]:
np.percentile(dados, 5), np.percentile(dados, 10), np.percentile(dados, 90)

(151.95000000000002, 152.89999999999998, 168.1)

In [56]:
stats.scoreatpercentile(dados, 5), stats.scoreatpercentile(dados, 10), stats.scoreatpercentile(dados, 90)

(151.95000000000002, 152.89999999999998, 168.1)

In [57]:
import pandas as pd
dataset = pd.DataFrame(dados)
dataset.head()

0
0  150
1  151
2  152
3  152
4  153

In [58]:
dataset.quantile([0.05, 0.10, 0.90])

0
0.05  151.95
0.10  152.90
0.90  168.10

### Exercício

In [59]:
dataset = pd.read_csv('census.csv')

In [60]:
dataset.head()

age          workclass  final-weight   education  education-num  \
0   39          State-gov         77516   Bachelors             13   
1   50   Self-emp-not-inc         83311   Bachelors             13   
2   38            Private        215646     HS-grad              9   
3   53            Private        234721        11th              7   
4   28            Private        338409   Bachelors             13   

        marital-status          occupation    relationship    race      sex  \
0        Never-married        Adm-clerical   Not-in-family   White     Male   
1   Married-civ-spouse     Exec-managerial         Husband   White     Male   
2             Divorced   Handlers-cleaners   Not-in-family   White     Male   
3   Married-civ-spouse   Handlers-cleaners         Husband   Black     Male   
4   Married-civ-spouse      Prof-specialty            Wife   Black   Female   

   capital-gain  capital-loos  hour-per-week  native-country  income  
0          2174             0             40   United-States   <=50K  
1             0             0             13   United-States   <=50K  
2             0             0             40   United-States   <=50K  
3             0             0             40   United-States   <=50K  
4             0             0             40            Cuba   <=50K

In [61]:
dataset['age'].mean()

38.58164675532078

In [62]:
stats.hmean(dataset['age'])

33.91874139089839

In [63]:
from scipy.stats.mstats import gmean
gmean(dataset['age'])

36.210879158177256

In [64]:
quadratic_mean(dataset['age'])

40.9218664329987

In [65]:
dataset['age'].median()

37.0

In [66]:
statistics.mode(dataset['age'])

36

### Medidas de dispersão

#### Amplitude total e diferença interquartil

In [69]:
dados

array([150, 151, 152, 152, 153, 154, 155, 155, 155, 155, 156, 156, 156,
       157, 158, 158, 160, 160, 160, 160, 160, 161, 161, 161, 161, 162,
       163, 163, 164, 164, 164, 165, 166, 167, 168, 168, 169, 170, 172,
       173])

In [70]:
dados.max() - dados.min()

23

In [71]:
q1 = np.quantile(dados, 0.25)
q3 = np.quantile(dados, 0.75)
q1, q3

(155.75, 164.0)

In [72]:
diferenca_interquartil = q3 - q1
diferenca_interquartil

8.25

In [73]:
inferior = q1 - (1.5 * diferenca_interquartil)
inferior

143.375

In [74]:
superior = q3 + (1.5 * diferenca_interquartil)
superior

176.375

#### Variância, desvio padrão e coeficiente de variação

In [75]:
dados_impar = np.array([150, 151, 152, 152, 153, 154, 155, 155, 155])

##### Cálculo Manual

In [76]:
media = dados_impar.sum() / len(dados_impar)
media

153.0

In [77]:
desvio = abs(dados_impar - media)
desvio

array([3., 2., 1., 1., 0., 1., 2., 2., 2.])

In [78]:
desvio = desvio ** 2
desvio

array([9., 4., 1., 1., 0., 1., 4., 4., 4.])

In [79]:
soma_desvio = desvio.sum()
soma_desvio

28.0

In [80]:
v = soma_desvio / len(dados_impar)
v

3.111111111111111

In [81]:
dp = math.sqrt(v)
dp

1.7638342073763937

In [82]:
cv = (dp / media) * 100
cv

1.1528328152786886

In [83]:
def get_variancia_desvio_padrao_coeficiente(dataset):
  media = dataset.sum() / len(dataset)
  desvio = abs(dados_impar - media)
  desvio = desvio ** 2
  soma_desvio = desvio.sum()
  variancia = soma_desvio / len(dados_impar)
  dp = math.sqrt(variancia)
  return variancia, dp, (dp / media) * 100

In [84]:
get_variancia_desvio_padrao_coeficiente(dados_impar)

(3.111111111111111, 1.7638342073763937, 1.1528328152786886)